(*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *)

let fibonacci max =
    let rec loop low high lis =
        if high > max then lis
        else loop high (low + high) (high :: lis)
    in
    loop 1 1 []
;;

let sum lis =
    List.fold_left (+) 0 lis
;;

let sum_of_even lis =
    sum (List.filter (fun x -> x mod 2 = 0) lis)
;;

Printf.printf "%d\n" (sum_of_even (fibonacci 4000000));;
