(*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *)

let rec fibonacci x =
    if x = 0 then 0
    else if x = 1 then 1
    else fibonacci (x - 1) + fibonacci (x - 2)
;;

let fibonacci_list max =
    let rec loop i lis =
        let x = fibonacci i
        in
            if x > max then lis
            else loop (i + 1) (x :: lis)
    in
        loop 1 []
;;

let sum lis =
    List.fold_left (+) 0 lis
;;

let sum_of_even lis =
    sum (List.filter (fun x -> x mod 2 = 0) lis)
;;

Printf.printf "%d\n" (sum_of_even (fibonacci_list 4000000));;
