;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(define fibonacci
    (lambda (x)
        (cond ((= x 1) 1)
              ((= x 2) 2)
              (else (+ (fibonacci (- x 1)) (fibonacci (- x 2)))))))

(define (fibonacci-lis max)
    (define (loop i lis)
        (let ((x (fibonacci i)))
            (if (> x max)
                lis
                (loop (+ i 1) (cons x lis)))))
    (loop 1 '()))

(define (sum lis)
    (fold + 0 lis))

(define (sum-of-even lis)
    (sum
        (filter even? lis)))

(print (sum-of-even (fibonacci-lis 4000000)))
