;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(define (fibonacci max)
  (define (loop low high lis)
    (if (> high max)
        lis
        (loop high (+ low high) (cons high lis))))
  (loop 1 1 '()))

(define (sum lis)
  (fold + 0 lis))

(define (sum-of-even lis)
  (sum (filter even? lis)))

(print (sum-of-even (fibonacci 4000000)))
