#!/usr/bin/env python
# -*- coding: utf-8 -*-
# python3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(max):
    lst = []
    low = 1
    high = 1
    while high < max:
        lst.append(high)
        high = low + high
        low = high - low
    return lst


total = 0
for i in fibonacci(4000000):
    if i % 2 == 0:
        total += i

print(total)
