// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(max) {
    def list = []
    def low = 1, high = 1
    while (high < max) {
        (low, high) = [high, low+high]
        list.push(low)
    }
    return list
}

def sum = 0
for (i in fibonacci(4000000)) {
    if (i % 2 == 0) {
        sum += i
    }
}
println sum
